databaseType = "SqlServer"
id = "63baa716-1a83-4dd4-8ff8-077979be85a4"
name = "NewGithubActionsPipeline"

[environments.build]
provisioner = "clean"

[environments.shadow]
provisioner = "clean"

[flyway]
baselineOnMigrate = true
baselineVersion = "001.20260925101351"
cleanDisabled = true
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

[flywayDesktop]
developmentEnvironment = "development"
schemaModel = "schema-model"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "Filter.scpf"
